version: '3'

services:
  myapp:
    build: .
    container_name: myapp
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html
  mysql: 
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql